// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlugEnt.BWA.Database;

#nullable disable

namespace SlugEnt.BWA.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlugEnt.BWA.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("CreatedByPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailExternal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedByPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("UPN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPersonId");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastModifiedByPersonId");

                    b.HasIndex("LastName");

                    b.HasIndex("UPN")
                        .IsUnique()
                        .HasFilter("[UPN] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SlugEnt.BWA.Entities.Models.User", b =>
                {
                    b.HasOne("SlugEnt.BWA.Entities.Models.User", "CreatedByPerson")
                        .WithMany()
                        .HasForeignKey("CreatedByPersonId");

                    b.HasOne("SlugEnt.BWA.Entities.Models.User", "LastModifiedByPerson")
                        .WithMany()
                        .HasForeignKey("LastModifiedByPersonId");

                    b.Navigation("CreatedByPerson");

                    b.Navigation("LastModifiedByPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
